INSERT INTO vessel_types (vessel_type_id, type_name) VALUES
(0, 'Not available'),
(1, 'Other (1-19 reserved range)'),
(2, 'Other (1-19 reserved range)'),
(3, 'Other (1-19 reserved range)'),
(4, 'Other (1-19 reserved range)'),
(5, 'Other (1-19 reserved range)'),
(6, 'Other (1-19 reserved range)'),
(7, 'Other (1-19 reserved range)'),
(8, 'Other (1-19 reserved range)'),
(9, 'Other (1-19 reserved range)'),
(10, 'Other (1-19 reserved range)'),
(11, 'Other (1-19 reserved range)'),
(12, 'Other (1-19 reserved range)'),
(13, 'Other (1-19 reserved range)'),
(14, 'Other (1-19 reserved range)'),
(15, 'Other (1-19 reserved range)'),
(16, 'Other (1-19 reserved range)'),
(17, 'Other (1-19 reserved range)'),
(18, 'Other (1-19 reserved range)'),
(19, 'Other (1-19 reserved range)'),
(20, 'Wing in ground (WIG) - all ships'),
(21, 'Wing in ground (WIG) - hazardous category A'),
(22, 'Wing in ground (WIG) - hazardous category B'),
(23, 'Wing in ground (WIG) - hazardous category C'),
(24, 'Wing in ground (WIG) - hazardous category D'),
(25, 'Wing in ground (WIG) - reserved'),
(26, 'Wing in ground (WIG) - reserved'),
(27, 'Wing in ground (WIG) - reserved'),
(28, 'Wing in ground (WIG) - reserved'),
(29, 'Wing in ground (WIG) - reserved'),
(30, 'Fishing'),
(31, 'Towing'),
(32, 'Towing (large dimensions)'),
(33, 'Dredging or underwater operations'),
(34, 'Diving operations'),
(35, 'Military operations'),
(36, 'Sailing vessel'),
(37, 'Pleasure craft'),
(38, 'Reserved'),
(39, 'Reserved'),
(40, 'High speed craft (HSC) - all'),
(41, 'HSC - hazardous A'),
(42, 'HSC - hazardous B'),
(43, 'HSC - hazardous C'),
(44, 'HSC - hazardous D'),
(45, 'HSC - reserved'),
(46, 'HSC - reserved'),
(47, 'HSC - reserved'),
(48, 'HSC - reserved'),
(49, 'HSC - no additional info'),
(50, 'Pilot vessel'),
(51, 'Search and rescue vessel'),
(52, 'Tug'),
(53, 'Port tender'),
(54, 'Anti-pollution vessel'),
(55, 'Law enforcement vessel'),
(56, 'Spare - local assignment'),
(57, 'Spare - local assignment'),
(58, 'Medical transport'),
(59, 'Ship (RR resolution 18)'),
(60, 'Passenger'),
(61, 'Passenger - hazardous A'),
(62, 'Passenger - hazardous B'),
(63, 'Passenger - hazardous C'),
(64, 'Passenger - hazardous D'),
(65, 'Passenger - reserved'),
(66, 'Passenger - reserved'),
(67, 'Passenger - reserved'),
(68, 'Passenger - reserved'),
(69, 'Passenger - no additional info'),
(70, 'Cargo'),
(71, 'Cargo - hazardous A'),
(72, 'Cargo - hazardous B'),
(73, 'Cargo - hazardous C'),
(74, 'Cargo - hazardous D'),
(75, 'Cargo - reserved'),
(76, 'Cargo - reserved'),
(77, 'Cargo - reserved'),
(78, 'Cargo - reserved'),
(79, 'Cargo - no additional info'),
(80, 'Tanker'),
(81, 'Tanker - hazardous A'),
(82, 'Tanker - hazardous B'),
(83, 'Tanker - hazardous C'),
(84, 'Tanker - hazardous D'),
(85, 'Tanker - reserved'),
(86, 'Tanker - reserved'),
(87, 'Tanker - reserved'),
(88, 'Tanker - reserved'),
(89, 'Tanker - no additional info'),
(90, 'Other type'),
(91, 'Other type - hazardous A'),
(92, 'Other type - hazardous B'),
(93, 'Other type - hazardous C'),
(94, 'Other type - hazardous D'),
(95, 'Other type - reserved'),
(96, 'Other type - reserved'),
(97, 'Other type - reserved'),
(98, 'Other type - reserved'),
(99, 'Other type - no additional info');

INSERT INTO nav_status (status_id, status_name) VALUES
(0, 'Under way using engine'),
(1, 'At anchor'),
(2, 'Not under command'),
(3, 'Restricted manoeuvrability'),
(4, 'Constrained by draught'),
(5, 'Moored'),
(6, 'Aground'),
(7, 'Engaged in fishing'),
(8, 'Under way sailing'),
(9, 'Reserved for future use'),
(10, 'Reserved for future use'),
(11, 'Power-driven vessel towing astern'),
(12, 'Power-driven vessel pushing ahead or towing alongside'),
(13, 'Reserved for future use'),
(14, 'AIS-SART (active)'),
(15, 'Undefined');